// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wutdo.api.Models;

namespace wutdo.api.Migrations
{
    [DbContext(typeof(WutdoContext))]
    [Migration("20180803143239_updatedPollAndAddedAnswerOptions")]
    partial class updatedPollAndAddedAnswerOptions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("wutdo.api.Models.AnswerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AnswerText");

                    b.Property<int?>("Order");

                    b.Property<int?>("PollId");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("AnswerOption");
                });

            modelBuilder.Entity("wutdo.api.Models.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Question");

                    b.HasKey("Id");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("wutdo.api.Models.AnswerOption", b =>
                {
                    b.HasOne("wutdo.api.Models.Poll", "Poll")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("PollId");
                });
#pragma warning restore 612, 618
        }
    }
}
